config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register' }
  resources :teams
  resources :feelings
  resources :users
  resources :welcomes, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feeling.rb
class Feeling < ApplicationRecord
  PURGATORY = 1
  UPSET = 2
  FRUSTRATED = 3
  SATISFIED = 4
  HEAVEN = 5
  belongs_to :user

  validates :day, presence: true
  validates :status, presence: true

  enum status: { heaven: HEAVEN, satisfied: SATISFIED, frustrated: FRUSTRATED, upset: UPSET, purgatory: PURGATORY }
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  ADMIN = 0
  BOSS = 1
  TEAMLEADER = 2
  EMPLOYEE = 3
  mount_uploader :avatar, AvatarUploader
  belongs_to :team, optional: true
  has_many :feelings, dependent: :destroy
  after_initialize :set_default_value
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :role, presence: true

  enum role: { admin: ADMIN, boss: BOSS, teamleader: TEAMLEADER, employee: EMPLOYEE }

  protected

  def set_default_value
    role || employee
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  protect_from_forgery prepend: true

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name, :lastname)
    end
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
  end
end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
  before_action :set_feeling, only: %i[show edit update destroy]

  # GET /feelings
  def index
    @feelings = policy_scope(Feeling)
    authorize @feelings
  end

  # GET /feelings/1
  def show; end

  # GET /feelings/new
  def new
    @feeling = Feeling.new
    authorize @feeling
  end

  # GET /feelings/1/edit
  def edit; end

  # POST /feelings
  def create
    @feeling = Feeling.new(feeling_params)
    authorize @feeling

    respond_to do |format|
      if @feeling.save
        format.html { redirect_to @feeling, notice: 'Feeling was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /feelings/1
  def update
    respond_to do |format|
      if @feeling.update(feeling_params)
        format.html { redirect_to @feeling, notice: 'Feeling was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /feelings/1
  def destroy
    @feeling.destroy
    respond_to do |format|
      format.html { redirect_to feelings_url, notice: 'Feeling was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feeling
    @feeling = Feeling.find(params[:id])
    authorize @feeling
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def feeling_params
    params.require(:feeling).permit(:day, :status, :user_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[show edit update destroy]

  # GET /teams
  def index
    @teams = policy_scope(Team)
    authorize @teams # This authorize actual user to work with these @teams
  end

  # GET /teams/1
  def show; end

  # GET /teams/new
  def new
    @team = Team.new
    authorize @team
  end

  # GET /teams/1/edit
  def edit; end

  # POST /teams
  def create
    @team = Team.new(team_params)
    authorize @team

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /teams/1
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /teams/1
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_team
    @team = Team.find(params[:id])
    authorize @team
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def team_params
    params.require(:team).permit(:name, :user_id)
  end

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(teams_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    # @users = User.all
    @users = policy_scope(User)
    authorize @users
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)
    authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :lastname, :email, :role, :password, :team_id, :avatar)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  # GET /welcome
  def index; end
end

app/views/feelings/1234_form.html.erb
<%= simple_form_for(@feeling) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :day %>
    <%= f.input :status, collection: Feeling.statuses.keys, selected: 4 %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feelings/1234edit.html.erb
<h1>Editing Feeling</h1>

<%= render 'form', feeling: @feeling %>

<%= link_to 'Show', @feeling %> |
<%= link_to 'Back', feelings_path %>

app/views/feelings/1234index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feelings</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feelings.each do |feeling| %>
      <tr>
        <td><%= feeling.day %></td>
        <td><%= feeling.status %></td>
        <td><%= feeling.user %></td>
        <td><%= link_to 'Show', feeling %></td>
        <td><%= link_to 'Edit', edit_feeling_path(feeling) %></td>
        <td><%= link_to 'Destroy', feeling, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feeling', new_feeling_path %>

app/views/feelings/1234new.html.erb
<h1>New Feeling</h1>

<%= render 'form', feeling: @feeling %>

<%= link_to 'Back', feelings_path %>

app/views/feelings/1234show.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeling</h1>

<p>
  <strong>Day:</strong>
  <%= @feeling.day %>
</p>

<p>
  <strong>Status:</strong>
  <%= @feeling.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @feeling.user_id %>
</p>

<%= link_to 'Edit', edit_feeling_path(@feeling) %> |
<%= link_to 'Back', feelings_path %>

app/views/feelings/_form.html.erb
<%= simple_form_for(@feeling) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :day %>
    <%= f.input :status, collection: Feeling.statuses.keys, selected: 4 %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feelings/_form.html.slim
= simple_form_for(@feeling) do |f|
  = f.error_notification

  .form-inputs
    = f.input :day
    = f.input :status, collection: Feeling.statuses.keys, selected: 4
    = f.association :user

  .form-actions
    = f.button :submit

app/views/feelings/edit.html.slim
h1 Editing Feeling with slim

= render 'form', feeling: @feeling

= link_to 'Show ', @feeling
| |
= link_to ' Back', feelings_path

app/views/feelings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feelings</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feelings.each do |feeling| %>
      <tr>
        <td><%= feeling.day %></td>
        <td><%= feeling.status %></td>
        <td><%= feeling.user %></td>
        <td><%= link_to 'Show', feeling %></td>
        <td><%= link_to 'Edit', edit_feeling_path(feeling) %></td>
        <td><%= link_to 'Destroy', feeling, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feeling', new_feeling_path %>

app/views/feelings/index.html.slim
p id="notice"
  = notice

h1 Feelings with slim

table
  thead
    tr
      th Day
      th Status
      th User
      th colspan="3"

  tbody
    - @feelings.each do |feeling|
      tr
        td = feeling.day
        td = feeling.status
        td = feeling.user_id
        td = link_to 'Show', feeling
        td = link_to 'Edit', edit_feeling_path(feeling)
        td = link_to 'Destroy', feeling, method: :delete, data: { confirm: 'Are you sure?' }

br
= link_to 'New Feeling', new_feeling_path

app/views/feelings/new.html.erb
<h1>New Feeling</h1>

<%= render 'form', feeling: @feeling %>

<%= link_to 'Back', feelings_path %>

app/views/feelings/new.html.slim
h1 New Feeling with slim

= render 'form', feeling: @feeling

= link_to 'Back', feelings_path

app/views/feelings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @feeling.day %>
</p>

<p>
  <strong>Status:</strong>
  <%= @feeling.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @feeling.user_id %>
</p>

<%= link_to 'Edit', edit_feeling_path(@feeling) %> |
<%= link_to 'Back', feelings_path %>

app/views/feelings/show.html.slim
p id="notice"
  = notice

h1 Feeling with slim

p
  strong Day:
  = @feeling.day

p
  strong Status:
  = @feeling.status

p
  strong User:
  = @feeling.user_id

= link_to 'Edit ', edit_feeling_path(@feeling)
| |
= link_to ' Back', feelings_path

app/views/layouts/1234application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nikoniko</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="users">Nikoniko</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', users_url %></li>
          <li><%= link_to 'Team', teams_url %></li>
          <li><%= link_to 'Feeling', feelings_url %></li>
        </ul>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div id="user_nav">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nikoniko</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="users">Nikoniko</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', users_url %></li>
          <li><%= link_to 'Team', teams_url %></li>
          <li><%= link_to 'Feeling', feelings_url %></li>
        </ul>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div id="user_nav">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
/comentario
/ = es render
/ - codigo que se ejecuta
html
  head
    title Nikoniko
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          li.navbar-brand= link_to 'Nikoniko', welcomes_url

        ul.nav.navbar-nav
          li.active = link_to 'Home', users_url
          li = link_to 'Team', teams_url
          li = link_to 'Feeling', feelings_url

    p.notice
      = notice
    p.alert
      = alert

    #user_nav
      - if user_signed_in?
          = "Signed in as #{current_user.email}. Not you?"
          = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        = link_to 'Sign up ', new_user_registration_path
        | or
        = link_to ' sign in', new_user_session_path

    = yield

app/views/users/1234_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :lastname %>
    <%= f.input :email %>
    <%= f.input :role, collection: User.roles.keys, selected: 3 %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/1234edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/1234index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New User', new_user_path %>
<% end %>

app/views/users/1234show.html.erb
<p id="notice"><%= notice %></p>

<h1>User</h1>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :lastname %>
    <%= f.input :email %>
    <%= f.input :role, collection: User.roles.keys, selected: 3 %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :lastname
    = f.input :email
    = f.input :role, collection: User.roles.keys, selected: 3
    = f.input :password
    = f.input :avatar, as: :file

  .form-actions
    = f.button :submit

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.slim
h1 Editing User with slim

= render 'form', user: @user

= link_to 'Show ', @user
| |
= link_to ' Back', users_path

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New User', new_user_path %>
<% end %>

app/views/users/index.html.slim
p id="notice"
  = notice

h1 Users with slim

table
  thead
    tr
      th Name
      th Lastname
      th Email
      th Role
      th colspan="3"

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.lastname
        td = user.email
        td = user.role
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

br
- if user_signed_in?
  = link_to 'New User', new_user_path

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.html.slim
h1 New User with slim

= render 'form', user: @user

= link_to 'Back', users_path

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.slim
p id="notice"
  = notice

h1 User with slim

p
  strong Name:
  = @user.name

p
  strong Lastname:
  = @user.lastname

p
  strong Email:
  = @user.email

p
  strong Role:
  = @user.role

= link_to 'Edit ', edit_user_path(@user)
| |
= link_to ' Back', users_path

app/views/welcomes/index.html.slim
h1 Info project with slim

h3 Enrique